### ISSUE TITLE
deepin linux build error

### ISSUE THREAD

**Issue by zhenruyan** [image-rs/deflate-rs#16]
error: macro undefined: 'assert_ne!'
  --> src/writer.rs:19:5
   |
19 |     assert_ne!(flush_mode, Flush::None);
   |     ^^^^^^^^^
   |
   = help: did you mean `assert_eq!`?

error: aborting due to previous error

error: Could not compile `deflate`.

thinks   

I am a beginner of rust

**Comment by oyvindln** [comment]
What version of rust are you using? assert_ne is a pretty new addition.

**Comment by moonfloof** [comment]
I'm also having this issue on Windows using MSVC. I've tried the stable, beta, and nightly channels and the error persists on all of them.

**Comment by oyvindln** [comment]
That's strange seeing as it was [added in rust 1.13](https://github.com/rust-lang/rust/blob/master/RELEASES.md#libraries-3). Though, if it's just that assert causing issues I can change it to use a normal assert in the next version instead..

**Comment by zhenruyan** [comment]
linux kernel 4.9.0 rustc 1.12.0

**Comment by oyvindln** [comment]
Right, you will need to update to at least 1.13.0 as the macro that is failing was added in that version. 

I will remove the usage of `assert_ne! `ianyhow n the next update of this crate as it's not really important.

**Comment by zhenruyan** [comment]
ok    thinks

**Comment by oyvindln** [comment]
I've removed the usage of assert_ne in the latest update. Do you still have this issue?

**Comment by oyvindln** [comment]
Closing this as the code no longer uses assert_ne!.
