### ISSUE TITLE
Assertion error from fuzzing

### ISSUE THREAD

**Issue by killercup** [image-rs/deflate-rs#17]
Fuzzing ([fuzzer code here](https://github.com/rust-fuzz/targets/tree/969350e0b52dee1cb9a89d20a03e395f6c95682c/deflate)) triggers an assertion error in [this line](https://github.com/oyvindln/deflate-rs/blob/8e1ec1e0cb36ffa6b62efc405a9fa056bff04a96/src/chained_hash_table.rs#L126) (looks like an overflow thing):

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `32767`, right: `0`)', /home/pascal/.cargo/git/checkouts/deflate-rs-44887ade842f84eb/8e1ec1e/src/chained_hash_table.rs:126
```

You can find the whole log here: <https://gist.github.com/killercup/f117fd4a55ba3855b74d04acdfaf46d5> (make sure to look at the crash file in raw mode; it's encoded as a raw Rust byte string).

**Comment by oyvindln** [comment]
Thanks! I will look into it. The assertion is meant to check that all the input data has been through the hash chains that are used to look for matches, so in the case assertions are disabled, this would at worst mean slightly worse compression ratio
