### ISSUE TITLE
debug assertion fails in writer.rs

### ISSUE THREAD

**Issue by uggwar** [image-rs/deflate-rs#18]
Hi!

Using deflate through the image crate generates a panic in debug mode on line 50 of writer.rs.

thread 'main' panicked at 'assertion failed: `(left == right)` (left: `60100`, right: `32769`)', /home/christer/.cargo/registry/src/github.com-1ecc6299db9ec823/deflate-0.7.8/src/writer.rs:50

**Comment by oyvindln** [comment]
Thanks for the report. Would it be posible to provide the data/image you used? I haven't managed to reproduce it.

**Comment by uggwar** [comment]
I'm following a tutorial on raytracers and the problem might very likely be in my code. :-)

Please have a look:
[stingray.tar.gz](https://github.com/oyvindln/deflate-rs/files/966012/stingray.tar.gz)

EDIT: Let me add that the assert started kicking in at version 0.7.7

**Comment by oyvindln** [comment]
It makes sense that it started in 0.7.7 since that was when the assertion was put in. I'm pretty sure it's a problem in deflate though, that assert shouldn't trigger on an user error.

**Comment by oyvindln** [comment]
It was definitely my error :), I think I've sorted it, there was an issue causing the compressor to end earlier than it should. Your code works fine for me with 0.7.9 now, let me know if it's fixed for you.

**Comment by uggwar** [comment]
0.7.9 fixed my issue. Thanks a lot! :-)

**Comment by Seeker14491** [comment]
I've triggered this same assertion on deflate 0.7.10. I am saving a 20,000 x 20,000 png image.

```
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `400020000`, right: `400052768`)', C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\deflate-0.7.10\src\writer.rs:50
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: <deflate::writer::ZlibEncoder<W>>::output_all
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot-cli/<panic macros>:8
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\deflate-0.7.10\src/writer.rs:189
   7: buddhabrot::bucket_field::nonatomic_bucket_field::NonatomicBucketField::save_png
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\deflate-0.7.10\src/writer.rs:196
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\png-0.7.0\src/encoder.rs:137
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.13.0\./src/png.rs:110
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot\src\bucket_field/nonatomic_bucket_field.rs:40
   8: buddhabrot_cli::run
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot\src/setup.rs:101
             at src/main.rs:46
   9: buddhabrot_cli::main
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot-cli/<quick_main macros>:4
  10: _rust_maybe_catch_panic
  11: std::rt::lang_start
  12: _tmainCRTStartup
  13: mainCRTStartup
  14: unit_addrs_search
```

**Comment by oyvindln** [comment]
That's a pretty large file, I will see if I can reproduce it.

**Comment by oyvindln** [comment]
Okay, I may or may not have fixed it in the last commit, does using deflate from the latest git solve the issue. Also, does it output a valid file in release mode?

**Comment by Seeker14491** [comment]
I'm still able to trigger the assert. I'm compiling with `opt-level = 3`.

```
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `400020000`, right: `400052768`)', C:\Users\Seekr\.cargo\git\checkouts\deflate-rs-44887ade842f84eb\f2c71f8\src\writer.rs:53
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: <deflate::writer::ZlibEncoder<W>>::output_all
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot-cli/<panic macros>:8
             at C:\Users\Seekr\.cargo\git\checkouts\deflate-rs-44887ade842f84eb\f2c71f8\src/writer.rs:183
   7: buddhabrot::bucket_field::nonatomic_bucket_field::NonatomicBucketField::save_png
             at C:\Users\Seekr\.cargo\git\checkouts\deflate-rs-44887ade842f84eb\f2c71f8\src/writer.rs:190
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\png-0.7.0\src/encoder.rs:137
             at C:\Users\Seekr\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.13.0\./src/png.rs:110
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot\src\bucket_field/nonatomic_bucket_field.rs:40
   8: buddhabrot_cli::run
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot\src/setup.rs:101
             at src/main.rs:46
   9: buddhabrot_cli::main
             at C:\Users\Seekr\projects\rust\single\Buddhabrot\buddhabrot-cli/<quick_main macros>:4
  10: _rust_maybe_catch_panic
  11: std::rt::lang_start
  12: _tmainCRTStartup
  13: mainCRTStartup
  14: unit_addrs_search
```

**Comment by oyvindln** [comment]
Okay, I managed to reproduce the issue thanks to rust-fuzz.

**Comment by oyvindln** [comment]
I think I've sorted this in the latest git, I will make a new release soon, does it solve your issue?

**Comment by Seeker14491** [comment]
Yes, I'm unable to trigger the assert now. Great work!

**Comment by oyvindln** [comment]
Okay, thanks for the report.

**Comment by lkolbly** [comment]
I'm getting this same assertion using 0.8.1: [issue18.tar.gz](https://github.com/image-rs/deflate-rs/files/3741738/issue18.tar.gz)
```
$ cargo run
    Updating crates.io index
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/conv`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `36725`,
 right: `69494`', /home/lane/.cargo/registry/src/github.com-1ecc6299db9ec823/deflate-0.8.1/src/writer.rs:54:5
```

(found originally trying to track down [this](https://github.com/image-rs/image-png/issues/147) issue, then I reduced the size of the crashing test data)

It looks like something about if the first block returns BufferFull, but that's about where my debugging prowess ends.

**Comment by oyvindln** [comment]
Will look into it.

**Comment by lkolbly** [comment]
I wasn't able to reproduce the issue just using deflate_bytes and sending the data all in one call. The issue18.tar.gz file contains good and bad data examples, base64 encoded such that each line is a different call to write_all on a ZlibEncoder.

**Comment by oyvindln** [comment]
Yeah I noticed. Found that if I disable the assertion the compressed data comes out wrong when I looked into it, so the assertion is working as intended in this case. Didn't have time to look into it further.

**Comment by lkolbly** [comment]
I guess that means that the debug assertion is working at least :D Let me know if there are any tests I can run to help.
