### ISSUE TITLE
AFL crash

### ISSUE THREAD

**Issue by aschampion** [image-rs/deflate-rs#39]
The AFL fuzz I started in #37 found a crash (after 37 days and 2 cycles!) where the decompressed data does not match the input (with `CompressionOptions::default()`). I'll look into in the next few days and also PR the fuzz binary. In the meantime here's the crash input.
[id:000000,sig:06,src:000831,op:havoc,rep:64.zip](https://github.com/image-rs/deflate-rs/files/3973436/id.000000.sig.06.src.000831.op.havoc.rep.64.zip)

**Comment by oyvindln** [comment]
Oh wow, will look into it in a week when I have time if no one else has found the issue by then.

**Comment by aschampion** [comment]
Last I checked there were 3 more unique crashes. I should note all of these are just the compression roundtrip data not matching the original data; no crashes in the library. I'll upload them next time I'm at that computer.

**Comment by aschampion** [comment]
The other 3: [crashes.zip](https://github.com/image-rs/deflate-rs/files/3995579/crashes.zip)
