### ISSUE TITLE
More AFL crashes

### ISSUE THREAD

**Issue by aschampion** [image-rs/deflate-rs#42]
These are the crashes found by #40 reported in #39 but not fixed by #41.

[remaining_failures.zip](https://github.com/image-rs/deflate-rs/files/4082749/remaining_failures.zip)

**Comment by oyvindln** [comment]
Okay, been a bit busy lately, but I'll look into it when I have time if someone hasn't gotten to it.

**Comment by Shnatsel** [comment]
This is pretty cool, thanks for the fuzzing!

You might want to add these bugs to https://github.com/rust-fuzz/trophy-case 😉

**Comment by oyvindln** [comment]
Hmm, something is causing an extra copy of the last byte to end up in the compressed stream.
