### ISSUE TITLE
Is this project only for deflate usage?

### ISSUE THREAD

**Issue by fredgan** [image-rs/deflate-rs#54]
Hi, I am not quite sure if this project is only used for `deflate`. If no, any further plan for `inflate` method?

**Comment by oyvindln** [comment]
There aren't any plans for it no. Initially I started this library to be a companion to the [inflate](https://crates.io/crates/inflate) crate, though both have mostly been superseded by using [flate2](https://crates.io/crates/flate2) with the rust back-end which serves the same purpose.

**Comment by fredgan** [comment]
Thanks!
