### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by oyvindln** [image-rs/deflate-rs#8]
Implement support for compression with a gzip header/trailer.

**Comment by ghost** [comment]
:+1:, any progress on this?

**Comment by oyvindln** [comment]
It's not something I have focused yet. I was planning to look at it after I've fixed the block splitting behaviour to emulate that of miniz/zlib (mostly done), and #7 (as these things don't require any API change). 

My idea for this issue was to use the code from flate2 to create a crate for gzip headers as suggested [here](https://github.com/alexcrichton/flate2-rs/issues/44) and use that. It should be relatively simple to implement as the gzip bits are after all just metadata and a checksum, and there are already crates for the checksum algorithm (CRC-32). Of course, anyone is welcome to contribute and it's very motivating to see someone interested in this.

**Comment by oyvindln** [comment]
Fixed in 8268a6778c102136ed428cf5868039afa3c1daa5

**Comment by ghost** [comment]
Awesome! Thanks!

**Comment by ghost** [comment]
You might want to update the README and state that the library is pure-Rust

**Comment by oyvindln** [comment]
It sort of says already, but I guess I could make it a bit clearer.
